- link:
    ~/bin:
      create: true
      relink: true
      glob: true
      path: bin/*
    ~/bin/git-friendly: vendor/git-friendly

- shell:
  -
    command: "mkdir -p ${HOME}/bin"
  -
    command: "chmod u+x ${HOME}/bin/*"
