- link:
    ~/.ctags.d/config.ctags: system/ctags

- shell:
  -
    command: "brew update -v"
    stdout: true
    stderr: true
  -
    description: "Installing Universal Ctags"
    command: "brew install --HEAD universal-ctags/universal-ctags/universal-ctags"
    stdout: true
    stderr: true
