- link:
    ~/.gitconfig: git/gitconfig
    ~/.gitignore.global: git/gitignore.global

- shell:
  -
    command: "brew update -v"
    stdout: true
    stderr: true
  -
    description: "Installing Git and Hub"
    command: "brew install git hub"
    stdout: true
    stderr: true
