- shell:
  -
    command: "brew update -v"
    stdout: true
    stderr: true
  -
    command: "brew upgrade"
  -
    command: "brew bundle --file=./homebrew/Brewfile.base"
    stdout: true
    stderr: true
  -
    command: "brew cleanup -v"
    stdout: true
    stderr: true
