- link:
    ~/.config/nvim: nvim

- shell:
  -
    command: "brew update -v"
    stdout: true
    stderr: true
  -
    description: "Installing Neovim"
    command: "brew install neovim"
    stdout: true
    stderr: true
  -
    description: "Installing python support for neovim"
    command: "brew install python3"
    stdout: true
    stderr: true
  -
    command: "pip3 install neovim"
    stdout: true
    stderr: true
