- shell:
  -
    description: "Installing rbenv"
    command: "brew install rbenv"
    stdout: true
    stderr: true
  -
    command: "rbenv init || true"
    stdout: true
    stderr: true
  -
    command: "curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash"
    stdout: true
    stderr: true