- link:
    ~/tmux-256color.terminfo: shell/tmux-256color.terminfo
    ~/xterm-256color-italic.terminfo: shell/xterm-256color-italic.terminfo

- shell:
  -
    command: "tic -x -v ${HOME}/xterm-256color-italic.terminfo"
    stdout: true
    stderr: true
  -
    command: "tic -x -v ${HOME}/tmux-256color.terminfo"
    stdout: true
    stderr: true
