- link:
    ~/tmux-256color.terminfo: resources/tmux-256color.terminfo
    ~/xterm-256color-italic.terminfo: resources/xterm-256color-italic.terminfo

- shell:
  -
    command: "tic -x -v ${HOME}/xterm-256color-italic.terminfo"
    stdout: true
    stderr: true
  -
    command: "tic -x -v ${HOME}/tmux-256color.terminfo"
    stdout: true
    stderr: true
  -
    command: "bash <(curl -s https://gist.githubusercontent.com/mikeschenkel/18d2d85f5cff9efb7a703266c7f0fc12/raw/24-bit-color-and-italics-test.sh)"
    stdout: true
