- link:
    ~/.tmux.conf: tmux/tmux.conf

- shell:
  -
    command: "brew update -v"
    stdout: true
    stderr: true
  -
    description: "Installing tmux"
    command: "brew install tmux"
    stdout: true
    stderr: true
  -
    command: "tmux source-file ~/.tmux.conf || true"
    stdout: true
    stderr: true
