- link:
    ~/.vimrc: vim/vimrc
    ~/.config/nvim/init.vim: vim/vimrc
    ~/.config/vim/plugin_settings: vim/plugin_settings

- shell:
  -
    description: "Installing Vim plugins"
    command: "nvim +PlugUpgrade +PlugInstall +PlugUpdate +PlugClean +qall"
    stdout: true
    stderr: true