- link:
    ~/.zshrc: zshrc
    ~/.zgenrc: zgenrc
    ~/.zgen: vendor/zgen
    ~/z.sh: vendor/z/z.sh
    ~/.aliases: aliases
    ~/.functions: functions

- shell:
  -
    command: "zsh"
  -
    description: "Change user shell to zsh"
    # command: "chsh -s /bin/zsh"
    # command: "chsh -s $(which zsh)"
    command: "sudo chsh -s /usr/local/bin/zsh $USER"
  -
    command: "zsh"