- link:
    ~/.zshrc: zshrc
    ~/.zgenrc: zgenrc
    ~/.zgen: vendor/zgen
    ~/z.sh: vendor/z/z.sh
    ~/.aliases: aliases
    ~/.functions: functions

- shell:
  - [zsh]
  -
    description: "Change user shell to zsh"
    command: "chsh -s /bin/zsh"
  - [zsh]
