- link:
    ~/.common_profile: common_profile
    ~/.bashenv: bashenv
    ~/.zshenv: zshenv
    ~/.zshrc: zshrc
    ~/.zsh/.aliases: zsh/aliases.sh
    ~/.zsh/.functions: zsh/functions.sh
    ~/.zsh/.fzf-base16.config: zsh/fzf-base16.config

- shell:
  -
    command: "zsh"
  -
    description: "Change user shell to zsh"
    command: "sudo chsh -s /usr/local/bin/zsh $USER"
  -
    command: "mkdir -p ${HOME}/.zsh/cache"
