- link:
    ~/.zshenv: zshenv
    ~/.zshrc: zshrc
    ~/.zgenrc: zgenrc
    ~/.zgen: vendor/zgen
    ~/z.sh: vendor/z/z.sh
    ~/.aliases: shell/aliases.sh
    ~/.functions: shell/functions.sh

- shell:
  -
    command: "zsh"
  -
    description: "Change user shell to zsh"
    command: "sudo chsh -s /usr/local/bin/zsh $USER"
