- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- link:
    ~/.vimrc: vimrc
    ~/.config/nvim/init.vim: vimrc
    ~/.config/vim/plugin_settings: vim/plugin_settings
    ~/.zsh/.fzf-base16.config: zsh/fzf-base16.config
    ~/.ctags.d/config.ctags: ctags
    ~/.gitconfig: git/gitconfig
    ~/.gitignore.global: git/gitignore.global

- shell:
  -
    description: "Installing submodules"
    command: "git submodule update --init --recursive"
  -
    command: "mkdir -p ${HOME}/.ssh/sockets"
  -
    command: "mkdir -p ${HOME}/repos"
  -
    command: "mkdir -p ${HOME}/labs"
