- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- link:
    ~/.config/nvim/after: vim/after
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/.config/nvim/init.vim: vimrc
    ~/.fzf-base16.config: shell/fzf-base16.config

- shell:
  -
    description: "Installing submodules"
    command: "git submodule update --init --recursive"
