- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- link:
    ~/.vim/plugin_settings:
      create: true
      relink: true
      glob: true
      path: vim/plugin_settings/*
    ~/.vimrc: vimrc
    ~/.config/nvim/init.vim: vimrc
    ~/.zsh/.fzf-base16.config: zsh/fzf-base16.config
    ~/.gitconfig: git/gitconfig
    ~/.gitignore.global: git/gitignore.global
    ~/bin:
      create: true
      relink: true
      glob: true
      path: bin/*

- shell:
  -
    description: "Installing submodules"
    command: "git submodule update --init --recursive"
  -
    command: "mkdir -p ${HOME}/bin"
    command: "chmod u+x ${HOME}/bin/*"
  -
    command: "mkdir -p ${HOME}/.ssh/sockets"
  -
    command: "mkdir -p ${HOME}/repos"
  -
    command: "mkdir -p ${HOME}/labs"
