- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- link:
    ~/.tmux.conf: tmux.conf

- shell:
  -
    description: "Installing submodules"
    command: "git submodule update --init --recursive"