- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- link:
    ~/.tmux.conf: tmux.conf
    ~/Brewfile: Brewfile

- shell:
  - [git submodule update --init --recursive, Installing submodules]

