- link:
    ~/Brewfile: Brewfile

- shell:
  -
    command: "brew update"
  -
    command: "brew upgrade"
  -
    command: "brew bundle"
    stdout: true
    stderr: true
  -
    command: "brew cleanup"
