- link:
    ~/.npmrc: npm/npmrc

- shell:
  -
    command: "brew update"
  -
    description: "Installing Node.js with npm"
    command: "brew install node"
    stdout: true
    stderr: true
  -
    description: "Installing Yarn"
    command: "brew install yarn"
    stdout: true
    stderr: true
  -
    command: "brew cleanup"
  -
    description: "Create a directory for global npm packages"
    command: "mkdir -p \"${HOME}/.npm-packages\""
  -
    description: "Globally install npm packges"
    command: "./npm/global-npm-packages.sh"
    stdout: true
    stderr: true
